name = "subs-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[dev]
port = 8977

[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
id = "0fe3512cddea4efda30957c36ce9e6d5"  #生產環境 ID
preview_id = "d64436260dad4d55929e7f2e638c5c4f"  # 預覽環境 ID